version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  myapp:
    image: myapp:latest
    depends_on:
      - db
    ports:
      - "8080:8080"